/*# Modelagem básica
 -ENTIDADE = TABELA 
 -CAMPO = ATRIBUTOS*/

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDEREÇO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSO DE MODELAGEM*/

/*FASE 01 E FASE 02 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL-RASCUNHO
MODELAGEM LÓGICA-QUALQUER PROGRAMA DE MODELAGEM

/*FASE 03 - DBA / AD*/

MODELAGEM FÍSICA

/*CRIANDO BANCO DE DADO*/

CREATE DATABASE PROJETO;

/*USANDO PROJETO*/

USE PROJETO;

/*CRIANDO A TABELA DE CLIENTES*/

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDEREÇO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO*/

SHOW TABLES;

USE PROJETO;

DESC CLIENTE;

/*TODO REGISTRO É CHAMADO DE TUPLA LINHA, CADA CÉLULA É UM CAMPO*/

/* SEMPRE QUE VC REINICIAR UM SGBD USE O COMANDO "USE"*/

/*DEU PROBLEMA NO CPF ERRO, PARA ALTERAR USE*/

ALTER TABLE CLIENTE
MODIFY CPF VARCHAR(11);

/*EXISTEM 3 MODOS DE INSERIR DADOS*/

/*MODO 1:*/

INSERT INTO CLIENTE VALUES (
'GUSTAVO',
'M',
'gustavoodenathpenha@hotmail.com',
'11813702993',
'43 98848-8958',
'rua das cabritas'
);

/*MODO 2:*/

INSERT INTO CLIENTE(NOME,SEXO,EMAIL,CPF,TELEFONE,ENDEREÇO) 
VALUES (
'ISABELA GAUTIER ONO',
'F',
'isabelaono@gmail.com',
'00000000000',
'16 997450600',
'rua das cabritas'
);

/*MODO 3:*/

/*ADICIONANDO DOIS OU MAIS AO MESMO TEMPO*/

INSER INTO CLIENTE VALUES (
'GISELE GAUTIER',
'F',
'giseleono@gmail.com',
'16 99722 2400',
'12345678910'
'rua das cabritas'
),
('ILADIO ONO',
'M',
'iladioono@gmail',
'16 9988 0255',
'12345678910'
'rua dos cachorros'
);

/* O COMANDO SELECT*/
/*SELEÇÃO , PROJEÇÃO E JUNÇÃO*/

SHOW DATABASE;

/*EXCLUSIVO DO MYSQ PONTEIRO PARA O DIC DE DADOS*/

SELECT NOW();

/*MOSTRA AS HORAS*/

SELECT 'GUSTAVO ODENATH';

SELECT 'LUIZ ANTONIO';

/*ALIAS DE COLUNA*/

SELECT NOW() AS DATA_HORA, 'GUSTAVO' AS PROFESSOR;

/*SELECT É PROJEÇÃO*/

/*SELECT É PROJEÇÃO*/

SELECT NOME AS CLIENTE , SEXO , EMAIL FROM CLIENTE;

/* NÃO DIGITE DIRETAMENTE NO BANCO*/

SELECT * FROM CLIENTE;

/*APENAS PARA FINS ACADEMICOS PQ O PROFISSIONAL DE TUNNNING VAI TE PEGAR*/

SELECT NOME AS CLIENTE, SEXO , EMAIL, NOW() AS DATA_HORA FROM CLIENTE;

/*SELEÇÃO É UTILIZADO O WHERE  FILTRANDO*/

SELECT NOME, EMAIL FROM CLIENTE
WHERE SEXO = 'F';

/*SELEÇÃO POR LIKE*/

SELECT NOME, EMAIL FROM CLIENTE
WHERE ENDEREÇO LIKE '% CABRITAS';

SELECT NOME, EMAIL, ENDEREÇO FROM CLIENTE
WHERE ENDEREÇO LIKE '% CABRITAS';








